
version: '3.3'

services:

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ./.env.db

    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql